name: pascal
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed: ^2.5.8
  intl: ^0.19.0
  qr_flutter: ^4.1.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.4

flutter:
  uses-material-design: true
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
  arb_dir: lib/core/utils/localization/l10n
  output_dir: lib/core/utils/localization/generated
